nacos:
  default:
    url: http://localhost:8848
    username: nacos
    password: nacos
    blacklist:
      - namespace: public
        group: DEFAULT_GROUP
        dataId: sss:ssss

database:
  db1:
    url: localhost
    port: 3306
    database: test
    username: root
    password: "1234"

logging:
  level: INFO
  format: "[%(asctime)s] %(levelname)s %(name)s %(message)s"
