# 日志配置
logging:
  level: INFO
  format: "[%(asctime)s] %(levelname)s %(name)s %(message)s"

# Nacos配置
nacos:
  default: # Nacos ID
    url: http://localhost:8848
    username: nacos
    password: nacos

# 数据库配置
database:
  db1: # Database ID
    url: localhost
    port: 3306
    username: root
    password: "12345678"
    dialect: mysql
    # liquibase的数据库变更日志表放入哪个schmea中，默认为liquibase
    changelogschema: liquibase
    secretmanager:
     aws:
        # 使用哪个 aws config profile访问aws-secretmanager
        profile: "default"
        # 密钥ID
        secretid: "arn:aws:secretsmanager:us-east-2:126026337867:secret:sit-meta-db-secret-V04N5t"    

config:
  database-uri: mysql+mysqlconnector://root:12345678@localhost:3306/test
  # 手动指定java-home目录，java版本必须在11及以上
  java-home-dir: 
  # Liquibase 运行配置文件
  liquibase:
    # Liquibase DATABASECHANGELOG 和 DATABASECHANGELOGLOCK 表存储在哪个schema
    schema-name: liquibase  
    # 配置文件
    defaults-file: 
    # 用户提供的 jdbc 驱动目录
    jdbc-drivers-dir: jdbc-drivers
