# 日志配置
logging:
  level: INFO
  format: "[%(asctime)s] %(levelname)s %(name)s %(message)s"

# Nacos配置
nacos:
  default: # Nacos ID
    url: http://localhost:8848
    username: nacos
    password: nacos

# 数据库配置
database:
  db1: # Database ID
    url: localhost
    port: 3306
    username: root
    password: "12345678"
    dialect: mysql
  vod-dev:
    url: dev-mfc-rds-nj.cchbpbfoxpjz.rds.cn-northwest-1.amazonaws.com.cn
    port: 3306
    username: ziyi_user
    password: snOzqqqNedKUnL94IClf
    dialect: mysql

config:
  database-uri: mysql+mysqlconnector://root:12345678@localhost:3306/test
  # 手动指定java-home目录，java版本必须在11及以上
  java-home-dir: 
  # Liquibase 运行配置文件
  liquibase:
    # 配置文件
    defaults-file: 
    # 用户提供的 jdbc 驱动目录
    jdbc-drivers-dir: 
