# Nacos配置
nacos:
  default: # Nacos ID
    url: http://localhost:8848
    username: nacos
    password: nacos

# 数据库配置
database:
  db1: # Database ID
    url: localhost
    port: 3306
    username: root
    password: "12345678"
    dialect: mysql
  vod-dev:
    url: dev-mfc-rds-nj.cchbpbfoxpjz.rds.cn-northwest-1.amazonaws.com.cn
    port: 3306
    username: ziyi_user
    password: snOzqqqNedKUnL94IClf
    dialect: mysql

# 日志配置
logging:
  level: INFO
  format: "[%(asctime)s] %(levelname)s %(name)s %(message)s"

config:
  database-uri: mysql+mysqlconnector://root:12345678@localhost:3306/test
