apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-ops
  namespace: devops
  labels:
    app: config-ops
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: config-ops
  template:
    metadata:
      labels:
        app: config-ops
    spec:
      automountServiceAccountToken: false
      containers:
        - image: $IMAGE
          name: config-ops
          resources:
            requests:
              cpu: "10m"
              memory: "55M"
            limits:
              cpu: "100m"
              memory: "128M"
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 5
            timeoutSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 5
            timeoutSeconds: 10
          imagePullPolicy: Always  
          env:
            - name: CONFIGOPS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: config-ops-config
                  key: config.yaml
          ports:
            - containerPort: 5000
              name: http

---
kind: Service
apiVersion: v1
metadata:
  name: config-ops
  namespace: devops
spec:
  selector:
    app: config-ops
  type: ClusterIP
  ports:
    - name: http
      port: 5000
      targetPort: 5000
