version: '2'
services:
  config-ops:
    image: wukaireign/config-ops:latest
    container_name: config-ops
    restart: always
    ports:
    - "5000:5000"
    environment:
      FLASK_RUN_HOST: 127.0.0.1
      FLASK_RUN_PORT: 5000
      # CONFIGOPS_CONFIG_FILE: 
      CONFIGOPS_CONFIG: |
        # Nacos配置
        nacos:
          default: # Nacos ID
            url: http://localhost:8848
            username: nacos
            password: nacos

        # 数据库配置
        database:
          db1: # Database ID
            url: localhost
            port: 3306
            username: root
            password: "1234"

        # 日志配置
        logging:
          level: INFO
          format: "[%(asctime)s] %(levelname)s %(name)s %(message)s"
              PORT: 5000
            ports:
              - '5000:5000'

        # 应用配置
        config:
          database-uri: sqlite:///configops.db
          # 手动指定java-home目录, java版本必须在11及以上
          java-home-dir: 
          # Liquibase 运行配置文件
          liquibase:
            # 配置文件
            defaults-file: 
            # 用户提供的 jdbc 驱动目录
            jdbc-drivers-dir: jdbc-drivers      