version: '2'
services:
  config-ops:
    image: wukaireign/config-ops:1.0.0
    container_name: config-ops
    restart: always
    ports:
    - "5000:5000"
    environment:
      # CONFIGOPS_CONFIG_FILE: 
      CONFIGOPS_HOST: 127.0.0.1
      CONFIGOPS_PORT: 5000
      CONFIGOPS_CONFIG: |
        # Nacos配置
        nacos:
          default: # Nacos ID
            url: http://localhost:8848
            username: nacos
            password: nacos

        # 数据库配置
        database:
          db1: # Database ID
            url: localhost
            port: 3306
            username: root
            password: "1234"

        # 日志配置
        logging:
          level: INFO
          format: "[%(asctime)s] %(levelname)s %(name)s %(message)s"
              PORT: 5000
            ports:
              - '5000:5000'