name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions: write-all

jobs:
  build-release:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller app.spec

      - name: Build Docker image
        run: |
          docker build -t wukaireign/config-ops:${{ github.ref_name }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push wukaireign/config-ops:${{ github.ref_name }}

      - name: Archive executable
        run: |
          cp config.yaml.sample dist/app
          cp README.md dist/app
          cp startup.sh dist/app
          cp docker-compose.yaml dist/app
          tar -czf config-ops-linux.tar.gz -C dist/app .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: config-ops-linux.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
