name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions: write-all

jobs:
  build-release:
    runs-on: ubuntu-latest
    container:
      image: wukaireign/python:3.9-ubuntu-18
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
          pip3 install pyinstaller

      - name: Build executable
        run: |
          pyinstaller app.spec

      - name: Archive executable
        run: |
          cp config.yaml.sample dist/app
          cp README.md dist/app
          cp startup.sh dist/app
          tar -czf config-ops-linux.tar.gz -C dist/app .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: config-ops-linux.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
